global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules/recording.rules.yml 
  - rules/watchdog.rules.yml
  - rules/prometheus.rules.yml
  - rules/infra.rules.yml
  - rules/storage.rules.yml
  - rules/services.rules.yml
  - rules/slo.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["atlas-alert:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          env: lab
          plane: boh
          service: prometheus

  - job_name: node
    file_sd_configs:
      - files: ["/etc/prometheus/targets/node.yml"]
        refresh_interval: 30s

  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files: ["/etc/prometheus/targets/blackbox_http.yml"]
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: atlas-blackbox-exporter:9115

  - job_name: blackbox_tcp
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
      - files: ["/etc/prometheus/targets/blackbox_tcp.yml"]
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: atlas-blackbox-exporter:9115
