- targets:
    - http://${MEDIA_STACK_HOST}:32400/web
  labels:
    env: lab
    plane: unraid
    service: atlas-plex
    check: http
    module: http_2xx
- targets:
    - http://${MEDIA_STACK_HOST}5:8989
  labels:
    env: lab
    plane: unraid
    service: atlas-sonarr
    check: http
    module: http_2xx
- targets:
    - http://${MEDIA_STACK_HOST}:7878
  labels:
    env: lab
    plane: unraid
    service: atlas-radarr
    check: http
    module: http_2xx
